github: https://github.com/
gitlab: https://gitlab.com/
gnu-ftp: https://ftpmirror.gnu.org/
gnu-git: https://git.savannah.gnu.org/git/
gnome-git: https://gitlab.gnome.org/
gnome-ftp: https://ftp.gnome.org/pub/GNOME/
fdo-git: https://gitlab.freedesktop.org/
fdo-ftp: https://www.freedesktop.org/software/
sourceware: https://sourceware.org/git/
kernel: https://git.kernel.org/pub/scm/
gnupg: https://dev.gnupg.org/source/
videolan: https://code.videolan.org/videolan/
xiph: https://gitlab.xiph.org/xiph/
chromium: https://chromium.googlesource.com/
sourceforge: https://sourceforge.net/projects/
webkitgtk: https://webkitgtk.org/releases/
google: https://dl.google.com/
efifs: https://efi.akeo.ie/downloads/efifs-1.6/
netfilter: http://git.netfilter.org/
ghostscript: http://git.ghostscript.com/
gnome_downloads: https://download.gnome.org/sources/
cairo_org: https://cairographics.org/
cdn_kernel_org: https://cdn.kernel.org/pub/
downloads.sourceforge.net: https://downloads.sourceforge.net/
ftp_gnu_org: https://ftp.gnu.org/gnu/
git_code_sf_net: https://git.code.sf.net/
git_freedesktop_org: https://gitlab.freedesktop.org/
gitlab_gnome_org: https://gitlab.gnome.org/
gnome_download: https://download.gnome.org/
gstreamer: https://gstreamer.freedesktop.org/src/
icon_theme_freedesktop_org: https://icon-theme.freedesktop.org/releases/
iso_codes: https://pkg-isocodes.alioth.debian.org/downloads/
libburnia: http://files.libburnia-project.org/releases/
people_freedesktop_org: https://people.freedesktop.org/
purism: https://source.puri.sm/
qqwing: https://qqwing.com/
sourceforge_net: https://sourceforge.net/projects/
spice: https://www.spice-space.org/download/
tarballs_needing_help: https://people.gnome.org/~mcatanzaro/tarballs-needing-help/
webkitgtk_org: https://webkitgtk.org/releases/