github: https://github.com/
gitlab: https://gitlab.com/
gnu-ftp: https://ftpmirror.gnu.org/
gnu-git: https://git.savannah.gnu.org/git/
gnome-git: https://gitlab.gnome.org/
gnome-ftp: https://ftp.gnome.org/pub/GNOME/
fdo-git: https://gitlab.freedesktop.org/
fdo-ftp: https://www.freedesktop.org/software/
sourceware: https://sourceware.org/git/
kernel: https://git.kernel.org/pub/scm/
gnupg: https://dev.gnupg.org/source/
videolan: https://code.videolan.org/videolan/
xiph: https://gitlab.xiph.org/xiph/
chromium: https://chromium.googlesource.com/
sourceforge: https://sourceforge.net/projects/
webkitgtk: https://webkitgtk.org/releases/
purism: https://source.puri.sm/
libburnia: http://files.libburnia-project.org/releases/
google: https://dl.google.com/
efifs: https://efi.akeo.ie/downloads/efifs-1.6/
netfilter: http://git.netfilter.org/
ghostscript: http://git.ghostscript.com/
