# Some overrides to element configuration based on type
#
# Here we can set a project wide options for various build systems,
# e.g. we can add --disable-gtk-doc to every `./configure` line.
elements:
  autotools:
    variables:
      conf-global: --disable-static --disable-Werror --host=%{triplet} --build=%{triplet}

  cmake:
    variables:
      cmake-global: -DCMAKE_BUILD_TYPE=RelWithDebInfo
      generator: Ninja

  distutils:
    variables:
      python-install: '%{python} setup.py install --root "%{install-root}"'
      fix-pyc-timestamps: ''
    config:
      install-commands:
        (>):
          # There's no way to get the setup.py to install this in the right place.
        - |
          if [ -d '%{install-root}/usr/lib/pkgconfig/' ]; then
            mkdir -p %{install-root}/usr/%{lib}/
            mv -f %{install-root}/usr/lib/pkgconfig/ %{install-root}/usr/%{lib}/
          fi

  meson:
    variables:
      meson-global: --buildtype=plain --auto-features=enabled