options:
  bootstrap_build_arch:
    type: arch
    description: Architecture
    variable: sandbox_arch
    values:
    - arm
    - aarch64
    - i686
    - x86_64
    - ppc64le

  target_arch:
    type: arch
    description: Architecture
    values:
    - arm
    - aarch64
    - i686
    - x86_64
    - ppc64le
