plugins:
- origin: pip
  package-name: buildstream-external
  sources:
    git_tag: 0
    cargo: 0
    x86image: 0
    collect_manifest: 0
    flatpak_image: 0
    flatpak_repo: 0

- origin: local
  path: plugins/elements
  elements:
    re_import: 0
    collect_initial_scripts: 0
    url_manifest: 1
