indep-libdir: "%{prefix}/lib"
sysconfdir: "/etc"
localstatedir: "/var"
gcc_arch: "%{arch}"
abi: "gnu"
gcc_triplet: "%{gcc_arch}-linux-%{abi}"
triplet: "%{arch}-unknown-linux-%{abi}"
lib: "lib/%{gcc_triplet}"
sbindir: "%{bindir}"
common_flags: "-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches"
flags_x86_64: "-march=x86-64 -mtune=generic %{common_flags} -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection %{local_flags}"
flags_i686: "-march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign %{common_flags} -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection %{local_flags}"
flags_aarch64: "%{common_flags} -fasynchronous-unwind-tables -fstack-clash-protection %{local_flags}"
flags_arm: "%{common_flags} %{local_flags}"
flags_ppc64le: "%{common_flags} -mcpu=power9 -mtune=power9 %{local_flags}"
ldflags_defaults: "-Wl,-z,relro,-z,now -Wl,--as-needed -L%{libdir}"
local_flags: ''



(@):
  - freedesktop-sdk.bst:include/strip.yml

(?):
 - arch == "i686":
      gcc_arch: "i386"
 - arch == "arm":
      abi: "gnueabihf"
 - arch == "ppc64le":
      gcc_arch: "powerpc64le"
