name: build-debug

on: [push, pull_request]

jobs:
    track:
      name: test
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            submodules: recursive

        - name: Setup Environment
          run: |
             sudo apt update 
             sudo apt install bubblewrap python3-bst-external
             pip3 install --user --pre BuildStream
             
        - name: Test
          run: bst track track.bst

        - name: "FAILED: Setup tmate session"
          if: ${{ failure() }}
          uses: mxschmitt/action-tmate@v3